# Start with a base image containing Java runtime
FROM java:8

# Make port 8080 available to the world outside this container
EXPOSE 9090

ADD target/filestorage-0.0.1-SNAPSHOT.jar filestorage-0.0.1-SNAPSHOT.jar

# Run the jar file 
ENTRYPOINT ["java","-jar","filestorage-0.0.1-SNAPSHOT.jar"]